import React from "react"
import './globals.css'
import Nav from './components/Nav'
import Providers from "./components/Providers"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">  

      <head>
        <title> Editor</title>
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/128/10728/10728539.png"/>
      </head>
      <body>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  )
}
